# Generated by Django 5.1.4 on 2026-06-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('allocated', 'Allocated'), ('purchased', 'Purchased')], max_length=20),
        ),
    ]
